url: https://blog.example42.com
title: Puppet Training, Consulting and Development. IT Automation and DevOps.
email: info@example42.com
author: Example42
description: > # "Example42 delivers Puppet training, consulting and development services. It provides consulting on automation and DevOps practices"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from

